site_name: qablet
theme:
  name: readthedocs
  icon:
    logo: material/triangle

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [qablet_contracts]

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math

nav:
  - 'index.md'
  - 'Getting Started': 'quickstart.md'
  - 'dataset.md'
  - 'assets.md'
  - 'Models':
    - 'Fixed': 'models/fixed.md'
    - 'Monte-Carlo': 'models/mc.md'
    - 'Finite-Difference': 'models/fd.md'
  - 'Stats':
    - 'stats/choices.md'
    - 'stats/pvvec.md'
